---
title: "2016 Election Margin"
output: html_notebook
---

This is an analysis of the margin of victory in the 2016 U.S. Presidential
Election. The workings of the U.S. Electoral college mean that narrow victories 
in key states can have a large impact on election results. This analysis
explores how many votes really decided the election. 

```{r setup, message=FALSE}
library(rvest)
library(tidyverse)
library(ggplot2)
library(testthat)

wiki <- read_html(paste0("https://en.wikipedia.org/wiki/",
                         "United_States_presidential_election,_2016"))
wiki_table <- html_node(wiki, 
                        xpath = '//*[@id="mw-content-text"]/div[38]/table') %>%
  html_table()

```


```{r munge}

# drop secondary header and total rows, keep popular and electoral vote counts
eresults_raw <- setNames(wiki_table[c(-1, -58), c(1, 3, 5, 6, 8)],
                     c("state", "h_popular", "h_electoral", "t_popular",
                       "t_electoral"))
eresults_raw %>% 
  mutate_each(funs(as.numeric(gsub(",", "", .))), -state) %>%
  mutate(margin = abs(h_popular - t_popular), 
         votes = pmax(h_electoral, t_electoral, na.rm = TRUE)) %>%
  left_join(tibble(state = state.name, st = state.abb), by = "state") ->
  eresults

weird_names <- c("District of Columbia", "Maine (at-large)", "Maine, 1st", 
                "Maine, 2nd", "Nebraska (at-lrg)", "Nebraska, 1st", 
                "Nebraska, 2nd", "Nebraska, 3rd")
eresults$st[match(c(weird_names) , eresults$state)] <- 
  c("DC", "ME", "ME1", "ME2", "NE", "NE1", "NE2", "NE3")

# district electoral college votes not conseuqnetial to this analysis, going to treat them as WTA
# for viz clarity
eresults$h_electoral[match("ME", eresults$st)] <- 
  sum(eresults$h_electoral[grep("ME", eresults$st)], na.rm = T)
# no votes for Hillary in NE, avaoid chaing NA to 0
# eresults$h_electoral[match("NE", eresults$st)] <- 
#   sum(eresults$h_electoral[grep("NE", eresults$st)], na.rm = T)

eresults$t_electoral[match("ME", eresults$st)] <- 
  sum(eresults$t_electoral[grep("ME", eresults$st)], na.rm = T)
eresults$t_electoral[match("NE", eresults$st)] <- 
  sum(eresults$t_electoral[grep("NE", eresults$st)], na.rm = T)

eresults <- filter(eresults, 
                   !st %in% c("ME1", "ME2", "NE1", "NE2", "NE3"))

eresults$votes[match("ME", eresults$st)] <- 
  sum(eresults[match("ME", eresults$st), c("h_electoral", "t_electoral")], na.rm = T)
eresults$votes[match("NE", eresults$st)] <- 
  sum(eresults[match("NE", eresults$st), c("h_electoral", "t_electoral")], na.rm = T)

# some calcs for plotting
eresults <- eresults %>%
  mutate(winner = ifelse(is.na(h_electoral), "Trump", "Clinton"),
         smargin = t_popular - h_popular) %>%
  arrange(-1 * smargin) %>%
  mutate(cum_vote  = cumsum(votes)) 


test_that("Electoral votes checksum", {
  expect_equal(
    sum(eresults$votes), 
    sum(eresults$h_electoral, na.rm = TRUE) + 
      sum(eresults$t_electoral, na.rm = TRUE)
  )
  expect_equal(sum(eresults$votes), 538)
})

eresults
```

```{r explore}

hist(eresults$margin)
hist(log10(eresults$margin))

```

```{r viz, fig.width=10}

flip_votes <- eresults %>%
  filter(st %in% c("MI", "WI", "PA")) %>%
  summarize(margin = sum(margin),
            cum_vote = max(cum_vote),
            votes = sum(votes)) %>%
  mutate(smargin = 0, winner = "Clinton")

margin_of_victory <- function(x) {
  paste0("Total Margin of Victory:\n", 
        prettyNum(x, big.mark = ","),
        " votes")
}

big_pretty_num <- function(x, short = FALSE) {
  m_lab <- ifelse(short, "M", " Million")
  k_lab <- ifelse(short, "K", " Thousand")
  x <- abs(x)
  p <- log10(x)
  labs <- ifelse(
    p >= 6, 
    paste0(signif(x / 1e6, 2), m_lab),
    paste0(signif(x / 1e3, 2), k_lab)
  )
  labs[x == 0] <- ""
  labs
}

plt <- eresults %>%
  ggplot(aes(xmin = cum_vote - votes, xmax = cum_vote,
             ymin = 0, ymax = smargin, 
             fill = winner)) +
  # 270 threshold
  geom_vline(xintercept = 270, size = 4,
             color = "grey90") +
  # margin bars
  geom_rect(aes(color = winner)) +
  # margin labels
  geom_text(aes(label = big_pretty_num(margin, TRUE),
                x = cum_vote - votes / 2, 
                y = smargin + 5e4 * ifelse(winner == "Trump", 1, -1)),
            data = filter(eresults, st %in% c("MI", "WI", "PA")),
            size = 2.5) +
  # State labels
  geom_text(aes(label = st, x = cum_vote - votes / 2,
                y = 100000 * ifelse(winner == "Trump", -1, 1)),
            angle = 90, size = 2.5) +
  # Margin of victory
  geom_errorbarh(aes(y = 2.3e5, x = cum_vote), data = flip_votes,
                 height = 1e5, size = 2) +
  geom_text(aes(y = 4.5e5, x = cum_vote - votes / 2, 
                label = margin_of_victory(margin)), 
            data = flip_votes, size = 4.5, fontface = "bold") +
  scale_x_continuous(labels = function(x) ifelse(x <= 270, x, 538 - x),
                     breaks = c(seq(0, 225, by = 75), 270,
                                rev(seq(538, 270, by = -75)))) +
  scale_y_continuous(labels = big_pretty_num,
                     breaks = c(-4e6, -2e6, -1e6, -5e5, -2.5e5, -5e4,
                                0, 5e4, 2.5e5, 5e5, 1e6),
                     minor_breaks = NULL) +
  coord_cartesian(ylim = c(-2e6, 1e6)) +
  scale_fill_manual(values = c("steelblue2", "tomato3")) +
  scale_color_manual(values = c("dodgerblue3", "firebrick4")) +
  theme_minimal() +
  theme(legend.position = "none",
        title = element_text(size = 18),
        axis.text = element_text(size = 13)) +
  labs(x = "Electoral College Votes",
       y = "Popular Vote Margin of Victory",
       title = "2016 U.S. Presidential Election Results",
       subtitle = "State Wins by Margin of Victory") +
  annotate("text", x = c(112.5, 538 - 112.5), y = c(-3e5, 3e5), 
           label = paste("States Won by", c("Trump", "Clinton")),
           size = 4) +
  annotate("text", x = 510.5, y = -2.05e6, size = 3, 
           label = "CA Truncated:\n4.3 Million") +
  annotate("text", x = 0, y = -2e6, color = "grey90", size = 6,
           label = "@DATATITIAN", hjust = 0, vjust = 0.9, fontface = "bold")
  
png("electionmargin.png", width = 10, height = 6, units = "in", res = 150)
print(plt)
invisible(dev.off())

plt

```









